import 'package:tune/features/home/models/bucket.dart';
import 'package:flutter/material.dart';
import 'package:tune/features/home/models/episode.dart';

const String _deepQuestionsImage =
    'https://i.scdn.co/image/ab67656300005f1f9fda39da7653f7d286908f60';
const String _jockoImage =
    'https://i.scdn.co/image/ab6765630000ba8a0537dba138113eef7649f3d8';
const String _lexImage =
    'https://cdn-images.dzcdn.net/images/talk/fa8715fd91b40c027dab37c6d6e91936/0x1900-000000-80-0-0.jpg';
const String _candaceImage =
    'https://m.media-amazon.com/images/S/dmp-catalog-images-prod/images/6feb6d45-4803-41bd-ab67-d08db6c85bb2/6feb6d45-4803-41bd-ab67-d08db6c85bb2--2068948825.jpg';
const String _merdivenImage =
    'https://i.scdn.co/image/ab67656300005f1f1c503861e62c316d3f6a7c81';
const String _navalImage =
    'https://podcastnotes.org/wp-content/uploads/2019/02/naval.jpg';
const String _kurcalaImage =
    'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/98/bf/0a/98bf0af3-01ce-9ab7-e1ab-6ec079f44cca/mza_7428743232472900956.jpg/600x600bb.jpg';
const String _alanWattsImage =
    'https://i.scdn.co/image/ab6765630000ba8a1bbd127cfafc8760b4ce9311';
const String _krishnamurtiImage =
    'https://krishnamurticentre.org.uk/wp-content/uploads/2020/05/0-banner-mobile-SFW.jpg';
const String _manpasiImage =
    'https://i.scdn.co/image/ab6765630000ba8ac0eaabc9372807788e548bdc';
const String _sohbetgahImage =
    'https://i.scdn.co/image/ab67656300005f1fc869eb49ed98bc5664c9990c';
const String _mehdiHasanImage =
    'https://www.siriusxmmedia.com/_next/image?url=https%3A%2F%2Fimage.simplecastcdn.com%2Fimages%2F8ba89b80-a681-4cd2-87bd-79a6315b0474%2F69e7f206-a859-4f9b-aa19-c5f769ead8f7%2Fthe-mehdi-hasan-show-showcast-1x1.jpg&w=3840&q=75';
const String _petersonImage =
    'https://i.scdn.co/image/ab6765630000ba8a91ca2e774aa8e57dd0f07a50';
const String _ycombinatorImage =
    'https://i.scdn.co/image/ab6765630000ba8a79fbc83dff3315e5a12e325d';
const String _stuffYouShouldKnowImage =
    'https://i.scdn.co/image/ab6765630000ba8ae8e4f69c2594c76b57b841f5';
const String _minimalistsImage =
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSea28FIAX01rBOWiD9cWSKChP5xIMx5FibaR3-wtUNoEdVEVUh32ObKpE&s=10';
const String _joeRoganImage =
    'https://i.scdn.co/image/ab67656300005f1f1e1acaebe06610165612f1ef';
const String _goodInsideImage =
    'https://m.media-amazon.com/images/M/MV5BYTUyOTkzMTUtMWVlNC00ZDMwLWJiNGUtNGE5NmMwMTAwZTlmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg';
const String _lennysImage =
    'https://i.scdn.co/image/ab6765630000ba8af45f22d94c8aea326e8bf861';
const String _officeLadiesImage =
    'https://upload.wikimedia.org/wikipedia/en/7/7c/Office_Ladies.png';

const List<Episode> mockEpisodes = <Episode>[
  Episode(
    bucket: Bucket.today,
    channel: 'Deep Questions',
    host: 'Cal Newport',
    title: 'How to Escape the Productivity Trap',
    date: 'Jun 26',
    seed: Color(0xFFB50801),
    image: _deepQuestionsImage,
    total: Duration(hours: 1, minutes: 14),
    listened: Duration(minutes: 22),
    playing: true,
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Candace',
    host: 'Candace Owens',
    title: 'Silence Is a Choice: On Gaza and Conscience',
    date: 'Jun 27',
    seed: Color(0xFFBE9200),
    image: _candaceImage,
    total: Duration(hours: 1, minutes: 38),
    listened: Duration(minutes: 49),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Jocko Podcast',
    host: 'Jocko Willink',
    title: 'Ownership and Extreme Accountability',
    date: 'Jun 26',
    seed: Color(0xFF000000),
    image: _jockoImage,
    total: Duration(hours: 2, minutes: 18),
    listened: Duration(hours: 1, minutes: 2),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Lex Fridman Podcast',
    host: 'Lex Fridman',
    title: 'Roger Penrose: Physics of the Mind',
    date: 'Jun 26',
    seed: Color(0xFF7D6D5E),
    image: _lexImage,
    total: Duration(hours: 2, minutes: 9),
    listened: Duration(minutes: 12),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Krishnamurti',
    host: 'Jiddu Krishnamurti',
    title: 'What Is Meditation, Really?',
    date: 'Jun 26',
    seed: Color(0xFF4D5C6C),
    image: _krishnamurtiImage,
    total: Duration(minutes: 58),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Lex Fridman Podcast',
    host: 'Lex Fridman',
    title: 'Black Holes, Time, and the Limits of Physics',
    date: 'Jun 25',
    seed: Color(0xFF7D6D5E),
    image: _lexImage,
    total: Duration(hours: 2, minutes: 47),
    listened: Duration(minutes: 33),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Candace',
    host: 'Candace Owens',
    title: 'The Truth About the Culture War',
    date: 'Jun 25',
    seed: Color(0xFFBE9200),
    image: _candaceImage,
    total: Duration(hours: 1, minutes: 36),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Deep Questions',
    host: 'Cal Newport',
    title: 'The Deep Reset',
    date: 'Jun 25',
    seed: Color(0xFFB50801),
    image: _deepQuestionsImage,
    total: Duration(hours: 1, minutes: 9),
    listened: Duration(hours: 1, minutes: 9),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Being in The Way',
    host: 'Alan Watts',
    title: 'The Art of Letting Go',
    date: 'Jun 25',
    seed: Color(0xFFA1836E),
    image: _alanWattsImage,
    total: Duration(hours: 1, minutes: 21),
    listened: Duration(minutes: 47),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Deep Questions',
    host: 'Cal Newport',
    title: 'Slow Productivity in a Busy World',
    date: 'Jun 24',
    seed: Color(0xFFB50801),
    image: _deepQuestionsImage,
    total: Duration(hours: 1, minutes: 5),
    listened: Duration(minutes: 14),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Merdiven Altı Terapi',
    host: 'Merdiven Altı Terapi',
    title: 'Kaygıyla Başa Çıkmak',
    date: 'Jun 23',
    seed: Color(0xFFCB3C2A),
    image: _merdivenImage,
    total: Duration(hours: 1, minutes: 12),
    listened: Duration(minutes: 34),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Naval',
    host: 'Naval Ravikant',
    title: 'How to Get Rich Without Getting Lucky',
    date: 'Jun 22',
    seed: Color(0xFFCBB08B),
    image: _navalImage,
    total: Duration(hours: 1, minutes: 2),
    listened: Duration(hours: 1, minutes: 2),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Jocko Podcast',
    host: 'Jocko Willink',
    title: 'Detach to Win the Hard Fights',
    date: 'Jun 21',
    seed: Color(0xFF000000),
    image: _jockoImage,
    total: Duration(hours: 1, minutes: 52),
    listened: Duration(minutes: 41),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Krishnamurti',
    host: 'Jiddu Krishnamurti',
    title: 'Freedom from the Known',
    date: 'Jun 21',
    seed: Color(0xFF4D5C6C),
    image: _krishnamurtiImage,
    total: Duration(hours: 1, minutes: 14),
    listened: Duration(hours: 1, minutes: 14),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Candace',
    host: 'Candace Owens',
    title: 'The War on Free Speech',
    date: 'Jun 20',
    seed: Color(0xFFBE9200),
    image: _candaceImage,
    total: Duration(hours: 1, minutes: 28),
    listened: Duration(minutes: 9),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Kurcala Podcast Yaptı',
    host: 'Nevzat Can Ünsal & Kaan Biber',
    title: 'Sınav stresiyle başa çıkmak',
    date: 'Jun 20',
    seed: Color(0xFF311732),
    image: _kurcalaImage,
    total: Duration(hours: 2, minutes: 6),
    listened: Duration(minutes: 52),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Lex Fridman Podcast',
    host: 'Lex Fridman',
    title: 'The Nature of Intelligence and Consciousness',
    date: 'Jun 12',
    seed: Color(0xFF7D6D5E),
    image: _lexImage,
    total: Duration(hours: 3, minutes: 12),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Being in The Way',
    host: 'Alan Watts',
    title: 'Accepting the Present Moment',
    date: 'Jun 14',
    seed: Color(0xFFA1836E),
    image: _alanWattsImage,
    total: Duration(hours: 1, minutes: 33),
    listened: Duration(hours: 1, minutes: 33),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Naval',
    host: 'Naval Ravikant',
    title: 'How to Be Happy: It Is a Skill',
    date: 'Jun 10',
    seed: Color(0xFFCBB08B),
    image: _navalImage,
    total: Duration(minutes: 49),
    listened: Duration(minutes: 49),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Jocko Podcast',
    host: 'Jocko Willink',
    title: 'Discipline Equals Freedom When It Gets Hard',
    date: 'Jun 8',
    seed: Color(0xFF000000),
    image: _jockoImage,
    total: Duration(hours: 2, minutes: 3),
    listened: Duration(hours: 2, minutes: 3),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Merdiven Altı Terapi',
    host: 'Merdiven Altı Terapi',
    title: 'İlişkilerde Sınır Koymak',
    date: 'Jun 7',
    seed: Color(0xFFCB3C2A),
    image: _merdivenImage,
    total: Duration(hours: 1, minutes: 4),
    listened: Duration(minutes: 18),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Kurcala Podcast Yaptı',
    host: 'Nevzat Can Ünsal & Kaan Biber',
    title: 'Bayram ziyaretinde faydalı bilgiler',
    date: 'Jun 5',
    seed: Color(0xFF311732),
    image: _kurcalaImage,
    total: Duration(hours: 2, minutes: 21),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Candace',
    host: 'Candace Owens',
    title: 'Hollywood and the Stories We Are Told',
    date: 'Jun 3',
    seed: Color(0xFFBE9200),
    image: _candaceImage,
    total: Duration(hours: 1, minutes: 41),
    listened: Duration(hours: 1, minutes: 41),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Lex Fridman Podcast',
    host: 'Lex Fridman',
    title: 'The Future of AI and Humanity',
    date: 'May 19',
    seed: Color(0xFF7D6D5E),
    image: _lexImage,
    total: Duration(hours: 2, minutes: 38),
    listened: Duration(hours: 2, minutes: 38),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Merdiven Altı Terapi',
    host: 'Merdiven Altı Terapi',
    title: 'Öz Şefkat Üzerine',
    date: 'May 6',
    seed: Color(0xFFCB3C2A),
    image: _merdivenImage,
    total: Duration(minutes: 57),
    listened: Duration(minutes: 57),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Naval',
    host: 'Naval Ravikant',
    title: 'Reading, Learning, and Compounding',
    date: 'Apr 22',
    seed: Color(0xFFCBB08B),
    image: _navalImage,
    total: Duration(minutes: 44),
    listened: Duration(minutes: 20),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Being in The Way',
    host: 'Alan Watts',
    title: 'Time and the More Abundant Life',
    date: 'Apr 9',
    seed: Color(0xFFA1836E),
    image: _alanWattsImage,
    total: Duration(hours: 1, minutes: 48),
    listened: Duration(hours: 1, minutes: 48),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Deep Questions',
    host: 'Cal Newport',
    title: 'Quitting the Internet for 30 Days',
    date: 'Apr 2',
    seed: Color(0xFFB50801),
    image: _deepQuestionsImage,
    total: Duration(hours: 1, minutes: 11),
    listened: Duration(hours: 1, minutes: 11),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Jocko Podcast',
    host: 'Jocko Willink',
    title: 'There Is No Easy Way Out',
    date: 'Mar 30',
    seed: Color(0xFF000000),
    image: _jockoImage,
    total: Duration(hours: 2, minutes: 27),
    listened: Duration(hours: 2, minutes: 27),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Krishnamurti',
    host: 'Jiddu Krishnamurti',
    title: 'On Fear and the Ending of Sorrow',
    date: 'Mar 28',
    seed: Color(0xFF4D5C6C),
    image: _krishnamurtiImage,
    total: Duration(hours: 1, minutes: 6),
    listened: Duration(hours: 1, minutes: 6),
  ),
  Episode(
    bucket: Bucket.earlier,
    channel: 'Kurcala Podcast Yaptı',
    host: 'Nevzat Can Ünsal & Kaan Biber',
    title: 'Burçlara göre arkadaş seçmek',
    date: 'Mar 21',
    seed: Color(0xFF311732),
    image: _kurcalaImage,
    total: Duration(hours: 1, minutes: 58),
    listened: Duration(hours: 1, minutes: 58),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'MANPASI',
    host: 'DJ Fateh & Rəvan Bağırov',
    title: 'Kimi şəxsən tanımasanız da ona simpatiyanız var',
    date: 'Jul 3',
    seed: Color(0xFFEF6C1A),
    image: _manpasiImage,
    total: Duration(hours: 1, minutes: 52),
    listened: Duration(minutes: 27),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'MANPASI',
    host: 'DJ Fateh & Rəvan Bağırov',
    title: 'Səhər söhbəti: yay istisi və şəhər həyatı',
    date: 'Jul 2',
    seed: Color(0xFFEF6C1A),
    image: _manpasiImage,
    total: Duration(hours: 1, minutes: 47),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'MANPASI',
    host: 'DJ Fateh & Rəvan Bağırov',
    title: 'Məsləhətli mövzu',
    date: 'Jun 30',
    seed: Color(0xFFEF6C1A),
    image: _manpasiImage,
    total: Duration(hours: 2, minutes: 3),
    listened: Duration(hours: 1, minutes: 14),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'MANPASI',
    host: 'DJ Fateh & Rəvan Bağırov',
    title: 'Dinləyici zəngləri və gündəm',
    date: 'Jun 18',
    seed: Color(0xFFEF6C1A),
    image: _manpasiImage,
    total: Duration(hours: 1, minutes: 41),
    listened: Duration(hours: 1, minutes: 41),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Söhbətgah',
    host: 'DJ Tural & Əli Xəyyam',
    title:
        'Azərbaycanda kino, aktyorluq, səhv bildiklərimiz | Kamran Ağabalayev',
    date: 'Jul 3',
    seed: Color(0xFF1F7A6B),
    image: _sohbetgahImage,
    total: Duration(hours: 2, minutes: 11),
    listened: Duration(minutes: 38),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Söhbətgah',
    host: 'DJ Tural & Əli Xəyyam',
    title: 'Alqoritmlər bizi necə idarə edir? | Müzəffər Qaraxanlı',
    date: 'Jul 2',
    seed: Color(0xFF1F7A6B),
    image: _sohbetgahImage,
    total: Duration(hours: 1, minutes: 56),
    listened: Duration(minutes: 15),
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Söhbətgah',
    host: 'DJ Tural & Əli Xəyyam',
    title: 'Qidalanma vərdişləri və sağlamlıq | Dr. Fərhad Burzu',
    date: 'Jun 29',
    seed: Color(0xFF1F7A6B),
    image: _sohbetgahImage,
    total: Duration(hours: 1, minutes: 44),
    listened: Duration(hours: 1, minutes: 44),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Söhbətgah',
    host: 'DJ Tural & Əli Xəyyam',
    title: 'Biznes, fintex və gələcək | Zeynal Kərimzadə',
    date: 'Jun 15',
    seed: Color(0xFF1F7A6B),
    image: _sohbetgahImage,
    total: Duration(hours: 2, minutes: 2),
    listened: Duration(minutes: 51),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'The Mehdi Hasan Show',
    host: 'Mehdi Hasan',
    title: "The Media's Gaza Blind Spot",
    date: 'Jul 3',
    seed: Color(0xFFB01E28),
    image: _mehdiHasanImage,
    total: Duration(hours: 1, minutes: 4),
    listened: Duration(minutes: 19),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'The Mehdi Hasan Show',
    host: 'Mehdi Hasan',
    title: 'Fact-Checking the Powerful, Live',
    date: 'Jul 2',
    seed: Color(0xFFB01E28),
    image: _mehdiHasanImage,
    total: Duration(minutes: 52),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'The Mehdi Hasan Show',
    host: 'Mehdi Hasan',
    title: 'Debating the Case for Free Speech Absolutism',
    date: 'Jun 28',
    seed: Color(0xFFB01E28),
    image: _mehdiHasanImage,
    total: Duration(hours: 1, minutes: 21),
    listened: Duration(minutes: 44),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'The Mehdi Hasan Show',
    host: 'Mehdi Hasan',
    title: 'Holding Power to Account: A Year of Zeteo',
    date: 'Jun 13',
    seed: Color(0xFFB01E28),
    image: _mehdiHasanImage,
    total: Duration(hours: 1, minutes: 12),
    listened: Duration(hours: 1, minutes: 12),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'The Jordan B. Peterson Podcast',
    host: 'Jordan B. Peterson',
    title: 'Meaning, Responsibility, and the Weight of Freedom',
    date: 'Jul 3',
    seed: Color(0xFF294B63),
    image: _petersonImage,
    total: Duration(hours: 1, minutes: 47),
    listened: Duration(minutes: 31),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'The Jordan B. Peterson Podcast',
    host: 'Jordan B. Peterson',
    title: 'The Psychology of the Biblical Stories',
    date: 'Jul 2',
    seed: Color(0xFF294B63),
    image: _petersonImage,
    total: Duration(hours: 2, minutes: 14),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'The Jordan B. Peterson Podcast',
    host: 'Jordan B. Peterson',
    title: 'Order, Chaos, and the Architecture of Belief',
    date: 'Jun 27',
    seed: Color(0xFF294B63),
    image: _petersonImage,
    total: Duration(hours: 1, minutes: 58),
    listened: Duration(hours: 1, minutes: 3),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'The Jordan B. Peterson Podcast',
    host: 'Jordan B. Peterson',
    title: 'On Discipline, Ambition, and the Life Worth Living',
    date: 'Jun 11',
    seed: Color(0xFF294B63),
    image: _petersonImage,
    total: Duration(hours: 2, minutes: 22),
    listened: Duration(hours: 2, minutes: 22),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Y Combinator',
    host: 'Y Combinator',
    title: 'How the Best Founders Find Their First Users',
    date: 'Jul 3',
    seed: Color(0xFFFB651E),
    image: _ycombinatorImage,
    total: Duration(minutes: 48),
    listened: Duration(minutes: 12),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Y Combinator',
    host: 'Y Combinator',
    title: 'Fundraising: What Actually Convinces Investors',
    date: 'Jul 2',
    seed: Color(0xFFFB651E),
    image: _ycombinatorImage,
    total: Duration(hours: 1, minutes: 3),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Y Combinator',
    host: 'Y Combinator',
    title: 'Building in the Age of AI Agents',
    date: 'Jun 26',
    seed: Color(0xFFFB651E),
    image: _ycombinatorImage,
    total: Duration(minutes: 55),
    listened: Duration(minutes: 40),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Y Combinator',
    host: 'Y Combinator',
    title: 'Lessons From 20 Years of Funding Startups',
    date: 'Jun 9',
    seed: Color(0xFFFB651E),
    image: _ycombinatorImage,
    total: Duration(hours: 1, minutes: 17),
    listened: Duration(hours: 1, minutes: 17),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Stuff You Should Know',
    host: 'Josh Clark & Chuck Bryant',
    title: 'How Bioluminescence Works',
    date: 'Jul 3',
    seed: Color(0xFFC65B4E),
    image: _stuffYouShouldKnowImage,
    total: Duration(minutes: 51),
    listened: Duration(minutes: 8),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Stuff You Should Know',
    host: 'Josh Clark & Chuck Bryant',
    title: 'The Wild History of the Ferris Wheel',
    date: 'Jul 2',
    seed: Color(0xFFC65B4E),
    image: _stuffYouShouldKnowImage,
    total: Duration(minutes: 47),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Stuff You Should Know',
    host: 'Josh Clark & Chuck Bryant',
    title: 'Short Stuff: Why Do We Hiccup?',
    date: 'Jun 27',
    seed: Color(0xFFC65B4E),
    image: _stuffYouShouldKnowImage,
    total: Duration(minutes: 18),
    listened: Duration(minutes: 18),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Stuff You Should Know',
    host: 'Josh Clark & Chuck Bryant',
    title: 'How Volcanoes Really Work',
    date: 'Jun 12',
    seed: Color(0xFFC65B4E),
    image: _stuffYouShouldKnowImage,
    total: Duration(hours: 1, minutes: 2),
    listened: Duration(minutes: 33),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'The Minimalists',
    host: 'Joshua Fields Millburn & Ryan Nicodemus',
    title: 'Owning Less, Living More',
    date: 'Jul 3',
    seed: Color(0xFF6E6E6E),
    image: _minimalistsImage,
    total: Duration(hours: 1, minutes: 6),
    listened: Duration(minutes: 21),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'The Minimalists',
    host: 'Joshua Fields Millburn & Ryan Nicodemus',
    title: 'How to Let Go of Sentimental Clutter',
    date: 'Jul 2',
    seed: Color(0xFF6E6E6E),
    image: _minimalistsImage,
    total: Duration(minutes: 58),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'The Minimalists',
    host: 'Joshua Fields Millburn & Ryan Nicodemus',
    title: 'Intentional Spending in a Consumer World',
    date: 'Jun 28',
    seed: Color(0xFF6E6E6E),
    image: _minimalistsImage,
    total: Duration(hours: 1, minutes: 14),
    listened: Duration(minutes: 47),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'The Minimalists',
    host: 'Joshua Fields Millburn & Ryan Nicodemus',
    title: 'Digital Declutter: Reclaiming Your Attention',
    date: 'Jun 10',
    seed: Color(0xFF6E6E6E),
    image: _minimalistsImage,
    total: Duration(hours: 1, minutes: 9),
    listened: Duration(hours: 1, minutes: 9),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'The Joe Rogan Experience',
    host: 'Joe Rogan',
    title: 'The Frontiers of Consciousness and Psychedelics',
    date: 'Jul 3',
    seed: Color(0xFF1A1A1A),
    image: _joeRoganImage,
    total: Duration(hours: 3, minutes: 4),
    listened: Duration(minutes: 26),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'The Joe Rogan Experience',
    host: 'Joe Rogan',
    title: 'Comedy, Combat Sports, and Staying Curious',
    date: 'Jul 2',
    seed: Color(0xFF1A1A1A),
    image: _joeRoganImage,
    total: Duration(hours: 2, minutes: 41),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'The Joe Rogan Experience',
    host: 'Joe Rogan',
    title: 'AI, Aliens, and the Future of Humanity',
    date: 'Jun 27',
    seed: Color(0xFF1A1A1A),
    image: _joeRoganImage,
    total: Duration(hours: 3, minutes: 18),
    listened: Duration(hours: 1, minutes: 52),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'The Joe Rogan Experience',
    host: 'Joe Rogan',
    title: 'Hunting, Health, and the Wild Within',
    date: 'Jun 8',
    seed: Color(0xFF1A1A1A),
    image: _joeRoganImage,
    total: Duration(hours: 2, minutes: 57),
    listened: Duration(hours: 2, minutes: 57),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Good Inside with Dr. Becky',
    host: 'Dr. Becky Kennedy',
    title: 'When Your Kid Falls Apart (and You Do Too)',
    date: 'Jul 3',
    seed: Color(0xFFD98E6A),
    image: _goodInsideImage,
    total: Duration(minutes: 42),
    listened: Duration(minutes: 15),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Good Inside with Dr. Becky',
    host: 'Dr. Becky Kennedy',
    title: 'Setting Boundaries Without Guilt',
    date: 'Jul 2',
    seed: Color(0xFFD98E6A),
    image: _goodInsideImage,
    total: Duration(minutes: 49),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Good Inside with Dr. Becky',
    host: 'Dr. Becky Kennedy',
    title: 'Raising Kids Who Trust Themselves',
    date: 'Jun 28',
    seed: Color(0xFFD98E6A),
    image: _goodInsideImage,
    total: Duration(minutes: 55),
    listened: Duration(minutes: 38),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Good Inside with Dr. Becky',
    host: 'Dr. Becky Kennedy',
    title: 'The Deepest Feelings Behind Tantrums',
    date: 'Jun 11',
    seed: Color(0xFFD98E6A),
    image: _goodInsideImage,
    total: Duration(minutes: 47),
    listened: Duration(minutes: 47),
  ),
  Episode(
    bucket: Bucket.today,
    channel: "Lenny's Podcast",
    host: 'Lenny Rachitsky',
    title: 'How Great Products Actually Get Built',
    date: 'Jul 3',
    seed: Color(0xFF4C6EF5),
    image: _lennysImage,
    total: Duration(hours: 1, minutes: 28),
    listened: Duration(minutes: 24),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: "Lenny's Podcast",
    host: 'Lenny Rachitsky',
    title: 'Finding Product-Market Fit, Step by Step',
    date: 'Jul 2',
    seed: Color(0xFF4C6EF5),
    image: _lennysImage,
    total: Duration(hours: 1, minutes: 12),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: "Lenny's Podcast",
    host: 'Lenny Rachitsky',
    title: 'Lessons on Growth From the Best in Tech',
    date: 'Jun 29',
    seed: Color(0xFF4C6EF5),
    image: _lennysImage,
    total: Duration(hours: 1, minutes: 41),
    listened: Duration(minutes: 55),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: "Lenny's Podcast",
    host: 'Lenny Rachitsky',
    title: 'Career Advice for Ambitious Builders',
    date: 'Jun 14',
    seed: Color(0xFF4C6EF5),
    image: _lennysImage,
    total: Duration(hours: 1, minutes: 19),
    listened: Duration(hours: 1, minutes: 19),
  ),
  Episode(
    bucket: Bucket.today,
    channel: 'Office Ladies',
    host: 'Jenna Fischer & Angela Kinsey',
    title: 'Booze Cruise: Behind the Scenes',
    date: 'Jul 3',
    seed: Color(0xFF2F6E8F),
    image: _officeLadiesImage,
    total: Duration(hours: 1, minutes: 11),
    listened: Duration(minutes: 17),
  ),
  Episode(
    bucket: Bucket.yesterday,
    channel: 'Office Ladies',
    host: 'Jenna Fischer & Angela Kinsey',
    title: 'The Dundies: Fan Questions Answered',
    date: 'Jul 2',
    seed: Color(0xFF2F6E8F),
    image: _officeLadiesImage,
    total: Duration(minutes: 58),
    listened: Duration.zero,
  ),
  Episode(
    bucket: Bucket.thisWeek,
    channel: 'Office Ladies',
    host: 'Jenna Fischer & Angela Kinsey',
    title: 'Casino Night: The One Where They Kiss',
    date: 'Jun 28',
    seed: Color(0xFF2F6E8F),
    image: _officeLadiesImage,
    total: Duration(hours: 1, minutes: 4),
    listened: Duration(minutes: 42),
  ),
  Episode(
    bucket: Bucket.thisMonth,
    channel: 'Office Ladies',
    host: 'Jenna Fischer & Angela Kinsey',
    title: 'Diversity Day: Where It All Began',
    date: 'Jun 12',
    seed: Color(0xFF2F6E8F),
    image: _officeLadiesImage,
    total: Duration(hours: 1, minutes: 9),
    listened: Duration(hours: 1, minutes: 9),
  ),
];
